<a href="https://colab.research.google.com/github/hasanshahriar32/pylearn/blob/main/computer_vision/tensorflow_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensorflow basics

In [1]:
import tensorflow as tf

tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [2]:
tensor_bool = tf.constant([True, False, True])
print(tensor_bool)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [3]:
tensor_one_d  = tf.constant([2, 0, -3, 8, 9], dtype=tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  8.  9.], shape=(5,), dtype=float32)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [4]:
tensor_string = tf.constant(["hello world", "hi"])

print(tensor_string)

tf.Tensor([b'hello world' b'hi'], shape=(2,), dtype=string)


In [5]:
## create 2D tensor from numpy

import numpy as np

np_array = np.array([1, 2, 4])
print([np_array])

converted_tensor = tf.convert_to_tensor(np_array)

[array([1, 2, 4])]
